
//Status Inquiry Response code
#define ROBOT_INFO_INQUIRY 11000
#define ROBOT_RUNNING_INFO_INQUIRY 11002
#define ROBOT_LOCATION_INQUIRY 11004
#define ROBOT_SPEED_INQUIRY 11005
#define ROBOT_BLOCKED_INQUIRY 11006
#define ROBOT_BATTERY_INQUIRY 11007
#define ROBOT_ESTOP_INQUIRY 110121
#define ROBOT_NAVIGATION_INQUIRY 11020
#define ROBOT_MAP_LOADING_INQUIRY 11022
#define ROBOT_ALARM_INQUIRY 11050
#define ROBOT_LOCALIZATION_STATUS_INQUIRY 11021
#define ROBOT_MAPLOADING_STATUS_INQUIRY 11022
#define ROBOT_MOTOR_STATUS_INQUIRY 11040
#define ROBOT_JACKING_STATUS_INQUIRY 11027

//Navigation task status
#define TASK_STAUTS_NONE 0
#define TASK_STAUTS_WAITING 1
#define TASK_STAUTS_RUNNING 2
#define TASK_STAUTS_SUSPENDED 3
#define TASK_STAUTS_COMPLETED 4
#define TASK_STAUTS_FAILED 5
#define TASK_STAUTS_CANCELED 6

//Navigation task_type
#define NO_NAVIGATION 0
#define FREE_ANY_POINT 1
#define FREE_STATION_POINT 2
#define PATH_NAVIGATION 3
#define TRANSLATIONAL_ROTATION 7
#define OTHER 100

//Task
#define ROTATION 1
#define TRANSLATION 2

#define PI 3.14159265359


//Alarm

#define ROBOT_BLOCKED 52200
#define ROBOT_ODO_LOST 52106
#define ROBOT_MOTOR_TIMEOUT 52111
#define ROBOT_CONFIDENCE_LOW 52300
#define ROBOT_NAVI_ERROR 52302
#define ROBOT_BATTERY_LOW 52503
#define ROBOT_PATH_PLANNING_FAIL 52702
#define ROBOT_CALIBRATION 54301

#define ROBOT_MAP_FILE_RESOLUTION 50105
#define ROBOT_MAP_FORMAT_ERROR 50106
#define ROBOT_BATTERY_TOO_LOW 50401
#define ROBOT_BATTERY_TEMPER_TOO_HIGH 50402


//Init
#define LOADING_MAP_FAILED 0
#define LOADING_MAP_SUCCESS 1
#define LOADING_MAP_LOADING 2

#define LOCALIZATION_FAILED 0
#define LOCALIZATION_SUCCESS 1
#define LOCALIZATION_RELOCING 2
#define LOCALIZATION_COMPLETED 3

#define INIT_START 0
#define INIT_RUNNING 1
#define INIT_DONE 2